apiVersion: v1
kind: Service

metadata:
 name: nginx-service

spec:
 selector: # labels are used as selectors
 # below labels are from 04-labels.yaml nginx pod
  project: roboshop
  component: frontend
  environment: dev

 ports:
 - protocol: TCP
   port: 80 # service port
   targetPort: 80 # containerport

    