apiVersion: v1
kind: Service

metadata:
 name: service-loadbalancer-nginx

spec:
 type: LoadBalancer
 
 selector: # the node port will be created for the pods having same selectors 
  project: roboshop
  component: frontend
  environment: dev

 ports:
 - protocol: TCP
   port: 80 #service port
   targetPort: 80  # container port
   